### ISSUE TITLE
spring config server :Cannot clone or checkout repository: https://gitlab.com/myproj//common/app-config/dev-config

### ISSUE THREAD

**Issue by sajadreshi** [spring-guides/gs-centralized-configuration#10]
I have simple spring boot config server application. My backend is gitlab and it is private repository. I can't get it working by providing authentication information. However, it works find with public repository in github.

My application yaml look like this.

```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/myproj/common/app-config/dev-config
          timeout: 10
          username: **myuser**
          password: **mypwd**
server:
 port: 8888    
```

Error I receieve

```
 Sat Jul 07 10:03:36 EDT 2018
There was an unexpected error (type=Not Found, status=404).
Cannot clone or checkout repository: https://gitlab.com/myproj/common/app-config/dev-config
```

Any suggestions would be appreciated.

**Comment by marcosnasp** [comment]
I am facing the same issue. I've tried to change the repo config (private to public), but it doesn't work. 
Meanwhile, I've set my uri config to "file:///", at this time, the error has gone, but the console shows the following message:

```console
2018-08-23 15:44:32.954  WARN 1275 --- [on(2)-127.0.0.1] .c.s.e.MultipleJGitEnvironmentRepository : Could not fetch remote for master remote: git@gitlab.com:marcosnasp/delivery-configs.git
```

**Comment by sajadreshi** [comment]
My problem was solved by adding **.git** towards the end of url.

 uri: https://gitlab.com/myproj/common/app-config/dev-config.git

**Comment by marcosnasp** [comment]
Thank you, I fixed the problem applying your config suggestion..

**Comment by imbarunsingh** [comment]
I also faced a similar problem with spring cloud config server. You need to add an additional property spring.cloud.config.server.git.skip-ssl-validation=true in application.properties file.
Checkout : https://stackoverflow.com/questions/50109704/spring-cloud-config-cannot-clone-or-checkout-repository-ssh-gitgithub-com

**Comment by wemgl** [comment]
@imbarunsingh Thanks, that worked perfectly for me.

**Comment by rupendra-sharma** [comment]
I am trying to use GItLab access token rather than using user name password combination, but it is not working. Has anyone tried this?
Sample url:
spring.cloud.config.server.git.uri=https://gitlab-ci-token:<private token>@git.example.com/myuser/myrepo.git
or
spring.cloud.config.server.git.uri=https://oauth2:ACCESS_TOKEN@somegitlab.com/vendor/package.git

**Comment by dsyer** [comment]
The second form works for me at gitlab.com (`oauth2:ACCESS_TOKEN`), but I think it depends on the GitLab version.

**Comment by LingboTang** [comment]
@imbarunsingh Actually I still have the problem after adding skip-ssl-validation: true in my application.yml

**Comment by LingboTang** [comment]
If someone has ignore-local-ssh-settings=true, you might get this error when you are using the ssh url, because you might not have local ssh settings sync to the remote git server. You should either disable this by setting it to true, or sync your ssh settings to the remote git server.

**Comment by burtsevyg** [comment]
> I am facing the same issue. I've tried to change the repo config (private to public), but it doesn't work.
> Meanwhile, I've set my uri config to "file:///", at this time, the error has gone, but the console shows the following message:
> 
> ```
> 2018-08-23 15:44:32.954  WARN 1275 --- [on(2)-127.0.0.1] .c.s.e.MultipleJGitEnvironmentRepository : Could not fetch remote for master remote: git@gitlab.com:marcosnasp/delivery-configs.git
> ```

Use native profile:
```
spring:
  profiles:
    active: "dev,native"

---

spring:
  profiles: dev
  cloud:
    config:
      server:
        native:
          search-locations: file://${PWD}/config

```
